name = "lapce-crates"
version = "0.0.1"
author = "Mathias Pius"
display-name = "Crates"
description = "Crates.io integration for Cargo.toml"
wasm = "bin/lapce-crates.wasm"
icon = "logo.png"
repository = "MathiasPius/lapce-crates"
dir = "/home/mpd/.local/share/lapce-stable/plugins/mathiaspius.lapce-crates/"

[activation]
language = ["rust"]
workspace-contains = ["**/Cargo.toml"]

[config."lsp.serverPath"]
default = ""
description = "Path to custom 'crates-lsp' executable. If you have not yet installed crates-lsp, go to https://github.com/MathiasPius/crates-lsp and follow the installation instructions."
