name = "lapce-crates"
version = "0.0.3"
author = "Mathias Pius"
display-name = "Crates"
description = "Crates.io integration for Cargo.toml"
wasm = "bin/lapce-crates.wasm"
icon = "logo.png"
repository = "https://github.com/MathiasPius/lapce-crates"
dir = "/home/mpd/.local/share/lapce-stable/plugins/mathiaspius.lapce-crates/"

[activation]
language = ["rust"]
workspace-contains = ["**/Cargo.toml"]

[config."lsp.serverPath"]
default = ""
description = "Version of crates-lsp to use, or path to local crates-lsp binary. Defaults to 'latest'."

[config."lsp.useApi"]
default = false
description = "Whether to make use of the crates.io api instead of the sparse index at https://index.crates.io\nUsing the API is highly discouraged as it puts unnecessary strain on the crates.io infrastructure, and provides no benefit over the sparse index."
