name = "lapce-crates"
version = "0.0.0"
author = "Mathias Pius"
display-name = "Crates"
description = "Crates.io integration for Cargo.toml"
wasm = "bin/lapce-crates.wasm"

[activation]
language = ["rust"]
workspace-contains = ["**/Cargo.toml"]

[config."lsp.serverPath"]
default = ""
description = "Path to custom LSP executable"
